### ISSUE TITLE
Seem to have an issue in working with Service principle login and Azure monitor

### ISSUE THREAD

**Issue by Sriram-Kumar1** [Azure/azure-docs-powershell-samples#348]
trying to use powershell to pull CPU usage metrics but keep failing with 

Exception type: AzPSApplicationException, Message: Microsoft.Azure.Commands.Common.Exceptions.AzPSApplicationException: No subscription found in the context.  Please ensure that the credentials you provided are authorized to access an Azure subscription, then run Connect-AzAccount to login.
   at Microsoft.Azure.Commands.Common.Authentication.Factories.ClientFactory.CreateArmClient[TClient](IAzureContext context, String endpoint)
   at Microsoft.Azure.Commands.Insights.ManagementCmdletBase.get_MonitorManagementClient()
   at Microsoft.Azure.Commands.Insights.Metrics.GetAzureRmMetricDefinitionCommand.ProcessRecordInternal()
   at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet(), Code: Null, Status code:Null, Reason phrase: Null

$conn = Get-AutomationConnection -Name 'AzureRunAsConnection'

#Connect-AzAccount -Tenant $conn.TenantId -ApplicationId $conn.ApplicationId -CertificateThumbprint $conn.CertificateThumbprint -ServicePrincipal

Add-AzureRmAccount -EnvironmentName "AzureCloud" -ServicePrincipal -TenantId $conn.TenantId -ApplicationId $conn.ApplicationId -CertificateThumbprint $conn.CertificateThumbprint 

$resourceManagerVMList = @(Get-AzureRmResource | where {$_.ResourceType -like "Microsoft.*/virtualMachines"} | sort Name)

    Write-Output "Processing [$($resourceManagerVMList.Count)] virtual machines found in subscription"
    foreach($vm in $resourceManagerVMList)
    {
        $vm1 = Get-AzureRmVM -ResourceGroupName $vm.ResourceGroupName -Name $vm.Name
        
        $resourceID = $vm1.Id
#        write-output "resource ID " $resourceID

        $endTime = Get-Date
        $startTime = $endTime.AddMinutes(-1440)
        $timeGrain = '00:01:00'
        $metricName = 'Percentage CPU'
        $metricData = Get-AzureRmMetric -ResourceId $resourceID -TimeGrain $timeGrain -StartTime $startTime -EndTime $endTime -MetricName $metricName
        Write-Output "[$($vm1.ResourceGroupName)]:[$($vm1.Location)]:[$($vm1.Name)]:[$($vm1.HardwareProfile.VmSize)]:[$($metricData)]"
        #break;
    }

**Comment by mikefrobbins** [comment]
@Sriram-Kumar1 Can you provide a link to the sample in this repo that you're experiencing issues with?
